2020-01-13 11:12:17 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 11:12:17 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 11:12:17 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 11:12:17 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 11:12:17 base.py[line:166] INFO Scheduler started
2020-01-13 11:13:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:13:00 CST)" (scheduled at 2020-01-13 11:13:00+08:00)
2020-01-13 11:13:03 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:14:00 CST)" executed successfully
2020-01-13 11:14:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:15:00 CST)" (scheduled at 2020-01-13 11:14:00+08:00)
2020-01-13 11:14:02 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:15:00 CST)" executed successfully
2020-01-13 11:15:16 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 11:15:16 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 11:15:16 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 11:15:16 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 11:15:16 base.py[line:166] INFO Scheduler started
2020-01-13 11:16:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:16:00 CST)" (scheduled at 2020-01-13 11:16:00+08:00)
2020-01-13 11:16:02 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='2-59', second='0'], next run at: 2020-01-13 11:17:00 CST)" executed successfully
2020-01-13 15:14:33 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:14:33 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:14:33 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:14:33 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:14:33 base.py[line:166] INFO Scheduler started
2020-01-13 15:15:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='15', second='0'], next run at: 2020-01-13 15:15:00 CST)" (scheduled at 2020-01-13 15:15:00+08:00)
2020-01-13 15:15:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='15', second='0'], next run at: 2020-01-13 16:15:00 CST)" executed successfully
2020-01-13 15:30:47 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:30:47 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:30:47 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:30:47 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:30:47 base.py[line:166] INFO Scheduler started
2020-01-13 15:31:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='31', second='0'], next run at: 2020-01-13 15:31:00 CST)" (scheduled at 2020-01-13 15:31:00+08:00)
2020-01-13 15:31:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='31', second='0'], next run at: 2020-01-13 16:31:00 CST)" executed successfully
2020-01-13 15:37:17 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:37:17 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:37:17 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:37:17 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:37:17 base.py[line:166] INFO Scheduler started
2020-01-13 15:37:41 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:37:41 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:37:41 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:37:41 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:37:41 base.py[line:166] INFO Scheduler started
2020-01-13 15:38:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='38', second='0'], next run at: 2020-01-13 15:38:00 CST)" (scheduled at 2020-01-13 15:38:00+08:00)
2020-01-13 15:38:05 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='38', second='0'], next run at: 2020-01-13 16:38:00 CST)" executed successfully
2020-01-13 15:45:21 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:45:21 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:45:21 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:45:21 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:45:21 base.py[line:166] INFO Scheduler started
2020-01-13 15:46:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='46', second='0'], next run at: 2020-01-13 15:46:00 CST)" (scheduled at 2020-01-13 15:46:00+08:00)
2020-01-13 15:46:03 base.py[line:131] ERROR Job "warning_disease (trigger: cron[hour='0-23', minute='46', second='0'], next run at: 2020-01-13 16:46:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\virtual_environment\time_series\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:/time_series_analize/main.py", line 71, in warning_disease
    save_warn_data(mc_test, t2_test, 2, dis_ls_test)
  File "E:\time_series_analize\utils\util.py", line 77, in save_warn_data
    mc.insertMany(sql, ls)
  File "E:\time_series_analize\baseClass\baseMysql.py", line 121, in insertMany
    count = self._cursor.executemany(sql, values)
  File "E:\virtual_environment\time_series\lib\site-packages\DBUtils\SteadyDB.py", line 605, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 199, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 199, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 165, in execute
    while self.nextset():
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 107, in nextset
    return self._nextset(False)
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 91, in _nextset
    conn = self._get_db()
  File "E:\virtual_environment\time_series\lib\site-packages\pymysql\cursors.py", line 73, in _get_db
    raise err.ProgrammingError("Cursor closed")
pymysql.err.ProgrammingError: Cursor closed
2020-01-13 15:47:06 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:47:06 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:47:06 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:47:06 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:47:06 base.py[line:166] INFO Scheduler started
2020-01-13 15:47:19 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:47:19 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:47:19 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:47:19 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:47:19 base.py[line:166] INFO Scheduler started
2020-01-13 15:48:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='48', second='0'], next run at: 2020-01-13 15:48:00 CST)" (scheduled at 2020-01-13 15:48:00+08:00)
2020-01-13 15:48:03 base.py[line:131] ERROR Job "warning_disease (trigger: cron[hour='0-23', minute='48', second='0'], next run at: 2020-01-13 16:48:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\virtual_environment\time_series\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:/time_series_analize/main.py", line 73, in warning_disease
    t_formal = WarningModel(mc_formal, five_data_formal).cal_frame
TypeError: __init__() takes 2 positional arguments but 3 were given
2020-01-13 15:49:10 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:49:10 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:49:10 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:49:10 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:49:10 base.py[line:166] INFO Scheduler started
2020-01-13 15:51:09 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:51:09 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:51:09 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:51:09 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:51:09 base.py[line:166] INFO Scheduler started
2020-01-13 15:51:14 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:51:14 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:51:14 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:51:14 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:51:14 base.py[line:166] INFO Scheduler started
2020-01-13 15:52:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='52', second='0'], next run at: 2020-01-13 15:52:00 CST)" (scheduled at 2020-01-13 15:52:00+08:00)
2020-01-13 15:52:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='52', second='0'], next run at: 2020-01-13 16:52:00 CST)" executed successfully
2020-01-13 15:54:45 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:54:45 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 15:54:45 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 15:54:45 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 15:54:45 base.py[line:166] INFO Scheduler started
2020-01-13 15:55:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='55', second='0'], next run at: 2020-01-13 15:55:00 CST)" (scheduled at 2020-01-13 15:55:00+08:00)
2020-01-13 15:55:03 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='55', second='0'], next run at: 2020-01-13 16:55:00 CST)" executed successfully
2020-01-13 16:05:34 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:05:34 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:05:34 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:05:34 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:05:34 base.py[line:166] INFO Scheduler started
2020-01-13 16:06:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='6', second='0'], next run at: 2020-01-13 16:06:00 CST)" (scheduled at 2020-01-13 16:06:00+08:00)
2020-01-13 16:06:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='6', second='0'], next run at: 2020-01-13 16:06:00 CST)" (scheduled at 2020-01-13 16:06:00+08:00)
2020-01-13 16:06:00 base.py[line:131] ERROR Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='6', second='0'], next run at: 2020-01-13 17:06:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\virtual_environment\time_series\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:/time_series_analize/main.py", line 66, in hand_foot_mouth
    generalPred(mc_test, handFootMouth.hfm_train_test, handFootMouth.hfm_test_test)
  File "E:/time_series_analize/main.py", line 40, in generalPred
    arima_test = ArimaModel(handFootMouth.hfm_train, handFootMouth.hfm_test, (2, 1, 1), (2, 1, 1, 12))
AttributeError: module 'data.handFootMouth' has no attribute 'hfm_train'
2020-01-13 16:06:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='6', second='0'], next run at: 2020-01-13 17:06:00 CST)" executed successfully
2020-01-13 16:10:23 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:10:23 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:10:23 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:10:23 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:10:23 base.py[line:166] INFO Scheduler started
2020-01-13 16:10:55 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:10:55 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:10:55 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:10:55 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:10:55 base.py[line:166] INFO Scheduler started
2020-01-13 16:11:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='11', second='0'], next run at: 2020-01-13 16:11:00 CST)" (scheduled at 2020-01-13 16:11:00+08:00)
2020-01-13 16:11:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='11', second='0'], next run at: 2020-01-13 16:11:00 CST)" (scheduled at 2020-01-13 16:11:00+08:00)
2020-01-13 16:11:04 base.py[line:144] INFO Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='11', second='0'], next run at: 2020-01-13 17:11:00 CST)" executed successfully
2020-01-13 16:11:05 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='11', second='0'], next run at: 2020-01-13 17:11:00 CST)" executed successfully
2020-01-13 16:14:39 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:14:39 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:14:39 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:14:39 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:14:39 base.py[line:166] INFO Scheduler started
2020-01-13 16:15:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='15', second='0'], next run at: 2020-01-13 16:15:00 CST)" (scheduled at 2020-01-13 16:15:00+08:00)
2020-01-13 16:15:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='15', second='0'], next run at: 2020-01-13 16:15:00 CST)" (scheduled at 2020-01-13 16:15:00+08:00)
2020-01-13 16:15:00 base.py[line:131] ERROR Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='15', second='0'], next run at: 2020-01-13 17:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\virtual_environment\time_series\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:/time_series_analize/main.py", line 74, in hand_foot_mouth
    generalPred(mc_test, handFootMouth.hfm_train_test, handFootMouth.hfm_test_test)
AttributeError: module 'data.handFootMouth' has no attribute 'hfm_train_test'
2020-01-13 16:15:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='15', second='0'], next run at: 2020-01-13 17:15:00 CST)" executed successfully
2020-01-13 16:16:52 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:16:52 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:16:52 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:16:52 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:16:52 base.py[line:166] INFO Scheduler started
2020-01-13 16:17:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='17', second='0'], next run at: 2020-01-13 16:17:00 CST)" (scheduled at 2020-01-13 16:17:00+08:00)
2020-01-13 16:17:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='17', second='0'], next run at: 2020-01-13 16:17:00 CST)" (scheduled at 2020-01-13 16:17:00+08:00)
2020-01-13 16:17:01 base.py[line:131] ERROR Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='17', second='0'], next run at: 2020-01-13 17:17:00 CST)" raised an exception
Traceback (most recent call last):
  File "E:\virtual_environment\time_series\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:/time_series_analize/main.py", line 75, in hand_foot_mouth
    generalPred(mc_formal, handFootMouth.hfm_train_formal, handFootMouth.hfm_test_formal)
AttributeError: module 'data.handFootMouth' has no attribute 'hfm_train_formal'
2020-01-13 16:17:03 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='17', second='0'], next run at: 2020-01-13 17:17:00 CST)" executed successfully
2020-01-13 16:17:50 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:17:50 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:17:50 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:17:50 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:17:50 base.py[line:166] INFO Scheduler started
2020-01-13 16:18:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='18', second='0'], next run at: 2020-01-13 16:18:00 CST)" (scheduled at 2020-01-13 16:18:00+08:00)
2020-01-13 16:18:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='18', second='0'], next run at: 2020-01-13 16:18:00 CST)" (scheduled at 2020-01-13 16:18:00+08:00)
2020-01-13 16:18:03 base.py[line:144] INFO Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='18', second='0'], next run at: 2020-01-13 17:18:00 CST)" executed successfully
2020-01-13 16:18:05 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='18', second='0'], next run at: 2020-01-13 17:18:00 CST)" executed successfully
2020-01-13 16:24:12 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:24:12 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:24:12 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:24:12 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:24:12 base.py[line:166] INFO Scheduler started
2020-01-13 16:24:29 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:24:29 base.py[line:440] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-01-13 16:24:29 base.py[line:881] INFO Added job "hand_foot_mouth" to job store "default"
2020-01-13 16:24:29 base.py[line:881] INFO Added job "warning_disease" to job store "default"
2020-01-13 16:24:29 base.py[line:166] INFO Scheduler started
2020-01-13 16:25:00 base.py[line:123] INFO Running job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='25', second='0'], next run at: 2020-01-13 16:25:00 CST)" (scheduled at 2020-01-13 16:25:00+08:00)
2020-01-13 16:25:00 base.py[line:123] INFO Running job "warning_disease (trigger: cron[hour='0-23', minute='25', second='0'], next run at: 2020-01-13 16:25:00 CST)" (scheduled at 2020-01-13 16:25:00+08:00)
2020-01-13 16:25:03 base.py[line:144] INFO Job "hand_foot_mouth (trigger: cron[month='1-12', day='13', hour='0-23', minute='25', second='0'], next run at: 2020-01-13 17:25:00 CST)" executed successfully
2020-01-13 16:25:04 base.py[line:144] INFO Job "warning_disease (trigger: cron[hour='0-23', minute='25', second='0'], next run at: 2020-01-13 17:25:00 CST)" executed successfully
